[package]
name = "spreadsheet-to-json-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
args = "2.2.0"
clap = { version = "^4.5.22", features = ["env", "derive"] }
dotenv = { version = "0.15.0", features = ["clap", "cli"] }
spreadsheet-to-json = "^0.1.0"
uuid = { version = "^1.11.0", features = ["fast-rng", "macro-diagnostics", "v4"] }
