[package]
name = "spreadsheet-to-json-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
args = "2.2.0"
clap = { version = "4.5.22", features = ["env", "derive"] }
spreadsheet-to-json = "0.1.0"

[patch.crates-io]
spreadsheet-to-json = { path = "../spreadsheet_to_json" }
